blank_issues_enabled: false
contact_links:
  - name: Support Questions & Other
    url: https://github.com/getcandy/getcandy/discussions
    about: 'If you have a question, or need some support from the community'
