name: npm-build
on:
  pull_request:
jobs:
  npm-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, amqp, dba
          tools: composer:v2

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Composer dependencies
        working-directory: ./packages/admin
        run: |
          composer install --no-interaction --prefer-dist

      - name: Install dependencies
        working-directory: ./packages/admin
        run: npm i

      - name: Build assets
        working-directory: ./packages/admin
        run: npm run build

      - name: Pull changes
        run: git pull

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: >
            chore: build assets
