name: npm-build
on:
  pull_request:
defaults:
  run:
    working-directory: ./packages/admin
jobs:
  npm-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 1.x

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Pull changes
        run: git pull

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: 1.x
          commit_message: >
            chore: build assets
