name: Scout DB Engine MySQL Tests
on:
  pull_request:
defaults:
  run:
    working-directory: ./
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.1, 8.2 ]
        laravel: [ 10.* ]
        phpunit-versions: [ 'latest' ]
    name: PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }}
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, amqp, dba, bcmath
          tools: composer:v2, phpunit:${{ matrix.php }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update --dev
          composer update --prefer-stable --no-interaction --no-suggest

      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_DATABASE: "test"
          DB_USERNAME: "root"
          DB_PASSWORD: "password"
        run: vendor/bin/pest  --testsuite scout-database-engine