name: Scout DB Engine Postgres Tests
on:
  pull_request:
defaults:
  run:
    working-directory: ./
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.1, 8.2 ]
        laravel: [ 10.* ]
        phpunit-versions: [ 'latest' ]
    name: PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }}
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, amqp, dba, bcmath
          tools: composer:v2, phpunit:${{ matrix.php }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update --dev
          composer update --prefer-stable --no-interaction --no-suggest

      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          APP_ENV: testing
          DB_CONNECTION: pgsql
          DB_HOST: postgres
          DB_DATABASE: "test"
          DB_USERNAME: "root"
          DB_PASSWORD: "password"
        run: vendor/bin/pest --testsuite scout-database-engine